// Code generated by mockery v2.32.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IBcryptHasher is an autogenerated mock type for the IBcryptHasher type
type IBcryptHasher struct {
	mock.Mock
}

// HashPassword provides a mock function with given fields: password
func (_m *IBcryptHasher) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyPassword provides a mock function with given fields: hashedPassword, enteredPassword
func (_m *IBcryptHasher) VerifyPassword(hashedPassword string, enteredPassword string) error {
	ret := _m.Called(hashedPassword, enteredPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hashedPassword, enteredPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIBcryptHasher creates a new instance of IBcryptHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBcryptHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBcryptHasher {
	mock := &IBcryptHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
